### ISSUE TITLE
个人简历

### ISSUE THREAD

**Issue by Princess310** [Princess310/Princess310.github.io#1]
# 联系方式

- 手机：18227552785 （四川雅安号）
- Email：onehower.princee@gmail.com / 837478514@qq.com (常用) 
- 微信号：princess310-
- QQ: 837478514

---

# 个人信息

 - 王浩/男/1994 
 - 本科/四川农业大学计算机科学与技术
 - 工作年限：2-3年
 - 技术博客：http://blog.onehower.com/
 - Github：https://github.com/Princess310

 - 期望职位：Web前端中高级程序员
 - 期望薪资：税前月薪12k~15k，特别喜欢的公司可例外
 - 期望城市：上海

---

# 工作经历

### 邀约项目
项目中，我主要负责项目官网( http://alijian.net/ )，webApp端，小程序(发供求)，微信分享活动页以及app里面嵌入的页面的开发。这个是公司第一个项目，移动端为主，用的是之前公司工作学习的briteJs框架，遇到的问题就是性能问题，缓存，各种第三方加载等各种移动端的问题，当时主要用gulp解决了很多问题，加上gzip压缩，线上页面打开1s-2s左右，自我感觉比较勉强，所以不断学习新技术再后面的项目中解决这些问题。

### 健康商信项目 
此项目是放弃邀约项目，基于之前的工作上做优化的一个项目。我主要负责pc端，webApp(微信公众号健康商信)，微信分享活动页以及app里面嵌入的页面的开发。这个项目我放弃了之前的技术框架，选择react以及周边技术，加上webpack，antd-mobile库，不仅解决了之前的性能问题，开发效率也不断提升。

### 舵狗项目
这个项目是类似定位拍照的一个想法，我主要负责完成了小程序(舵狗)，pc端( http://doggo.alijian.net/ )的开发。因为pc端需要SEO优化，我选择了用vue的服务端渲染方案，LightHouse测试SEO 100%，达到理想中状态。

 
### OA项目 
这个项目主要负责完善之前没有完成的模块，登录，用户管理，消息通知等模块。

### 当季商城项目 
这个项目是基于别人的系统开发的，我主要负责维护一些购物车，清单等模块的页面。

## BriteSnow公司 （ 2014年9月 ~ 2015年8月 ）
这段工作经历是作为大学生时，被老师介绍去做的外包工作，给老外打工，全职工作，学习了很多东西，接触了很多优质项目，所以感觉可以放入简历里面讲一讲

### briteCRM项目 
客户管理系统，这个项目主要负责客户详情 contact页面，contactList页面，project以及projectList页面的后端处理和前端页面的开发。

### OCI项目
一个云端文件管理系统，作为team leader，负责分发每天的任务给开发人员，根据开发进度调整开发速度。同时主要负责文件系统，关系分类等后端开发和维护工作。

### 其他项目
其他还接触了sampleSocial(社区管理)，ISONAS(门禁管理系统)，JSS(云端关于投过简历的搜索系统)，老外节奏有时比较快，接触的项目都是比较优质的，自我感觉除了学习到老外自己写的框架BriteSnow，J8ql这些，更重要的是学习到了团队的合作，工作安排流程如何高效有序。

# 技能清单

以下均为我熟练使用的技能

- Web开发：HTML5/CSS3/Node
- Web框架：BriteSnow
- 前端框架：Bootstrap/ReactJs/VueJs
- 前端工具：Webpack/Gulp/SaSS/LeSS
- 数据库相关：MySQL/PgSQL
- 版本管理：Git
- 单元测试：Jest

## 参考技能关键字

- web
- javascript
- css
- jquery
- html5
- java
- photoshop
- github
- webapp

---

# 致谢
感谢您花时间阅读我的简历，期待能有机会和您共事。

**Comment by DoongGe** [comment]
哥们，github上能找到工作吗？
